### ISSUE TITLE
Is it possible to test partial html?

### ISSUE THREAD

**Issue by eko3alpha** [rexxars/html-validator#10]
My interest in this plugin is to validate HTML partials from a textarea in a CMS.  Is there a parser option to allow for partial HTML testing?  If I validate only the partial HTML I get the following errors.

```
"Element “head” is missing a required instance of child element “title”."
"Start tag seen without seeing a doctype first. Expected “<!DOCTYPE html>”."
```

This is understandable as this is testing a full HTML page.  I found a workaround by wrapping the HTML with html/title/body tags, but it would more convenient to allow for partial HTML checking.

Thanks!

**Comment by rexxars** [comment]
I agree, but the API does not support this. I also solved it by wrapping it in a well-formed document, for what it's worth.
