### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NoBodyButMe** [rexxars/html-validator#11]
I run PHP 5.6 and use version 2 of your validator. 
When I add the following rules, I receive a 500 server-error: 
$result = $validator->validateDocument($document);
echo $result;

I see this error message: Fatal error: Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://checker.html5.org?out=json&parser=html4` resulted in a `502 Bad Gateway`

**Comment by rexxars** [comment]
Not much I can do about this, the HTML5.org validator seems to be down :(
