### ISSUE TITLE
Validator.nu down again

### ISSUE THREAD

**Issue by esetnik** [rexxars/html-validator#4]
502 from validator.nu :-1: 

it looks like this is a recurring issue:
https://github.com/mozilla/html5-lint/issues/22

maybe we should switch to a local validator that accepts piped data or possibly https://validator.w3.org/nu/

**Comment by rexxars** [comment]
Yeah, sucks, but not much I can do about it. Changing to a different validator would just move the point of failure somewhere else. The library does support setting the hostname, however, so you could set up your own validator https://github.com/rexxars/html-validator#using-a-self-hosted-version-of-the-api

**Comment by esetnik** [comment]
Yeah I only mentioned the w3.org option because nobody seems to be consistently complaining about that one. And w3.org shouldn't go down as much since w3 literally invented the internet :smile_cat:. Point taken though i'll experiment with the w3 validator domain and report back.
