### ISSUE TITLE
Guzzle isn't up-to-date

### ISSUE THREAD

**Issue by webserviceXXL** [rexxars/html-validator#5]
`guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)`

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

**Comment by rexxars** [comment]
Just released `2.0.0` which requires PHP 5.6 and uses `guzzlehttp/guzzle` instead of `guzzle/guzzle`.
