### ISSUE TITLE
validator.nu is down

### ISSUE THREAD

**Issue by esetnik** [rexxars/html-validator#6]
See https://github.com/validator/validator/issues/325

**Comment by rexxars** [comment]
Not really much I can do about this. Sorry.

**Comment by esetnik** [comment]
Could we switch to one of the other validator relays such as https://checker.html5.org? This was suggested in validator/validator#325

I tried to follow the instructions https://github.com/rexxars/html-validator#using-a-self-hosted-version-of-the-api to use checker.html5.org but it didn't work.

**Comment by rexxars** [comment]
The one you linked to doesn't seem to be the same codebase - it didn't expose the same validator endpoints that return JSON responses. I don't want to scrape HTML to get the result back, but if you find a different validator with an API...

**Comment by esetnik** [comment]
The default validator is returning a 500 error now

```
GuzzleHttp\Exception\ServerException: Server error: `POST https://validator.nu?out=json&parser=html5` resulted in a `500 Internal Server Error` response:
<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server E (truncated...)
```

but I just switched to `$validator = new HtmlValidator\Validator('http://validator.w3.org/nu/');` and it's working again.
