### ISSUE TITLE
The W3C CSS Validation Service

### ISSUE THREAD

**Issue by denavin** [rexxars/html-validator#9]
Hi,  
I try to retrieve data from **css-validator** and I get : 
_Server did not respond with the expected content-type (application/json)_
Call like this : 
$validator = new Validator('https://jigsaw.w3.org/css-validator/');

By the way, thank you for your api

**Comment by rexxars** [comment]
The CSS validator seems to have a [SOAP API](https://jigsaw.w3.org/css-validator/api.html) instead of the JSON API which the HTML5 validator has. As this module is primarily meant to validate HTML, I'm not going to support this - sorry.
